import {db} from './db'; import {getDeviceId,id,now,todayKey} from './ids'; import {queueOperation} from './sync'; import {rolloverState,type DeferDecision,validateDeferral} from './rollover'; import type {Project,Task,TaskEvent} from '../types';
const owner='local';
async function event(taskId:string,type:TaskEvent['type'],extra:Partial<TaskEvent>={}){const value:TaskEvent={id:id(),ownerId:owner,taskId,type,occurredAt:now(),...extra};await db.taskEvents.add(value);await queueOperation({deviceId:getDeviceId(),entityType:'task_event',entityId:value.id,baseVersion:0,kind:'create',fields:value as unknown as Record<string,unknown>})}
export async function captureTask(title:string){const stamp=now();const task:Task={id:id(),ownerId:owner,createdAt:stamp,updatedAt:stamp,version:1,title:title.trim(),descriptionMarkdown:'',status:'inbox',priority:3,energy:'medium',estimateConfidence:'low',nextActionText:'',deferCount:0,rolloverState:'clear',sortOrder:Date.now()};await db.tasks.add(task);await event(task.id,'task_created');await queueOperation({deviceId:getDeviceId(),entityType:'task',entityId:task.id,baseVersion:0,kind:'create',fields:task as unknown as Record<string,unknown>});return task}
export async function createProject(title:string){const stamp=now();const project:Project={id:id(),ownerId:owner,createdAt:stamp,updatedAt:stamp,version:1,title:title.trim(),purpose:'',definitionOfDone:'',status:'active'};await db.projects.add(project);await queueOperation({deviceId:getDeviceId(),entityType:'project',entityId:project.id,baseVersion:0,kind:'create',fields:project as unknown as Record<string,unknown>});return project}
export async function updateTask(task:Task,fields:Partial<Task>){const updated={...task,...fields,updatedAt:now(),version:task.version+1};await db.tasks.put(updated);await queueOperation({deviceId:getDeviceId(),entityType:'task',entityId:task.id,baseVersion:task.version,kind:'update_fields',fields:fields as Record<string,unknown>});return updated}
export async function planToday(task:Task){const commitments=await db.tasks.where('plannedForDate').equals(todayKey()).filter(x=>x.status!=='done'&&!x.deletedAt).count();if(commitments>=3)throw new Error('Today is intentionally limited to three commitments.');const value=await updateTask(task,{status:'planned',plannedForDate:todayKey(),rolloverState:'clear'});await event(task.id,'task_planned');return value}
export async function completeTask(task:Task,minutes?:number){const value=await updateTask(task,{status:'done',completedAt:now(),rolloverState:'clear'});if(minutes)await event(task.id,'actual_time_logged',{minutes});await event(task.id,'task_completed');return value}
export async function deferTask(task:Task,decision:DeferDecision,nextAction?:string,date?:string){const error=validateDeferral(task,decision,nextAction);if(error)throw new Error(error);const count=task.deferCount+1;const status=decision==='drop'?'dropped':decision==='delegate'?'delegated':'deferred';const value=await updateTask(task,{status,deferCount:count,lastDeferReason:decision,nextActionText:nextAction?.trim()||task.nextActionText,plannedForDate:decision==='reschedule'?date:undefined,rolloverState:rolloverState(count)});await event(task.id,decision==='drop'?'task_dropped':'task_deferred',{metadata:{decision}});return value}
export async function logTimer(task:Task,minutes:number){if(minutes>0)await event(task.id,'actual_time_logged',{minutes})}
